//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Etl.MarketPrice
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarketPrice
    {
        public int price_id { get; set; }
        public string market { get; set; }
        public System.DateTime candle_date_time_utc { get; set; }
        public System.DateTime candle_date_time_kst { get; set; }
        public double opening_price { get; set; }
        public double high_price { get; set; }
        public double low_price { get; set; }
        public double trade_price { get; set; }
        public long timestamp { get; set; }
        public double candle_acc_trade_price { get; set; }
        public double candle_acc_trade_volume { get; set; }
        public long unit { get; set; }
        public System.DateTime regdate { get; set; }
    }
}
