//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Etl.MarketPrice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Summary
    {
        public int summary_id { get; set; }
        public string market { get; set; }
        public Nullable<System.DateTime> candle_date_time_utc { get; set; }
        public Nullable<System.DateTime> candle_date_time_kst { get; set; }
        public Nullable<double> opening_price { get; set; }
        public Nullable<double> high_price { get; set; }
        public Nullable<double> low_price { get; set; }
        public Nullable<double> trade_price { get; set; }
        public Nullable<long> timestamp { get; set; }
        public Nullable<double> candle_acc_trade_price { get; set; }
        public Nullable<double> candle_acc_trade_volume { get; set; }
        public Nullable<long> unit { get; set; }
        public Nullable<bool> redcandle { get; set; }
        public Nullable<double> avg_5 { get; set; }
        public Nullable<double> avg_10 { get; set; }
        public Nullable<double> avg_20 { get; set; }
        public Nullable<double> volume_multiple { get; set; }
        public Nullable<double> price_multiple { get; set; }
        public Nullable<double> avg_5_coef { get; set; }
        public Nullable<double> avg_10_coef { get; set; }
        public Nullable<double> avg_20_coef { get; set; }
        public Nullable<bool> posi_coef { get; set; }
        public Nullable<bool> correct_order_avg { get; set; }
        public string cate { get; set; }
        public Nullable<System.DateTime> regdate { get; set; }
    }
}
